### ISSUE TITLE
Plugin should not show completion for the word that start with digits

### ISSUE THREAD

**Issue by ooopscc** [FuzzyAutocomplete/FuzzyAutocompletePlugin#58]
For instance, I am type for CGRect, if I type 100 or somewhat, completion panel will show up, it is annoying. Because completion for numbers is meaningless (for me）
Hope update for this issue or make this into a feature that we can turn off.
Thanks for the amazing plugin.

Below is the completion options when I type '10'
![snip20150109_15](https://cloud.githubusercontent.com/assets/1056803/5681137/8e040530-9850-11e4-9026-1b909758e59d.png)

**Comment by slazyk** [comment]
I agree, I don't remember this being the case some time ago, so maybe the chars that trigger completion session in Xcode have changed (because of crazy identifiers possible in Swift?).

I don't think this should be an option, it should not pop up on itself for numbers. If somebody will really want to complete for a number they can always `^Space`...

**Comment by oronbz** [comment]
agree, this is really annoying
