### ISSUE TITLE
Allow "Exact match" suggestions.

### ISSUE THREAD

**Issue by atheken** [FuzzyAutocomplete/FuzzyAutocompletePlugin#84]
Hey all, thanks for working on this plugin.

One thing I'm running into is that usually I know the word I'm searching for, but I don't know the message name in it's entirety.

So, I might type ".draw" , and I would expect a list of options that had that word in it. This, I think is different than the current matching, which searches for each letter, d, r, a, w in order. For my case, this seems like it really slows down the completion engine a lot, and in most cases, generates some noisy results for me.

If I were to work on a feature that allowed "exact match" anywhere in the completion list, would this project be open to accepting it as a PR? Obviously, code quality, standards and a review would be required before the project would merge any such contribution.

**Comment by atheken** [comment]
Make the issue title more obvious.

**Comment by slazyk** [comment]
Yes, that is correct, fuzzy matching works more or less the way you described.

As for search performance and noisy results, tinker a little bit with options you have in settings, noise can be substantially reduced by either setting the threshold higher. Results closer to what you want can also be achieved by manipulating scoring parameters. (You can enable display of timings and scores in options to play a bit.)

And yes, pull requests are welcome, and feature you described sounds useful.

My initial thoughts on the feature:

It would either have to be limited to a single substring (which sounds very limited), or have some mechanism for searching for multiple words, e.g.:

- split `camelHumps` into searching for both `camel` and `Humps`
- introduce some hotkey/character to indicate word boundary

And if it does allow to search for multiple words, then it might make sense to try supporting word order correction. I.e. searching for `RangeMake` should find both `NSMakeRange` and `CGRangeMake` (there is a similar experimental feature already allows you to make one mistake in the order with fuzzy match, but with whole words there is less combinations so probably it might make sense to just search for all the combinations explicitly).

And make sure to:
- make it an option than can be toggled, or triggered with a hotkey
- after finding the first letter do a binary search (on completions ordered by suffix starting on match) instead of linear search to filter down, because otherwise you probably won't be gaining much performance

I also think that use-case of searching with the new "word match" followed by the old "fuzzy match" makes sense, even when there are some results, but the user decides they want to see more.
